#!/bin/bash

function showCommands()
{
  echo "Usage: cazel <command> <target>"
  echo ""
  echo "Available commands:"
  echo "  sync   - Synchronize depends from server."
  echo "  build  - Build target project by cmake."
  echo "  auto   - execute sync and build command."
  echo "  clean  - Clean obj files."
  echo "  remove - Remove all build and depends directories."
}

function commandComplete()
{
  # to be implemented
  return 0
}

function main()
{
  local command=$1
  shift
  case $command in
    "sync"):
    dr_sync $@
    ;;
    "build"):
    dr_make $@
    ;;
    "auto"):
    dr_sync $@
    dr_make $@
    ;;
    "re-auto"):
    dr_remove $@
    dr_sync $@
    dr_make $@
    ;;
    "clean"):
    dr_clean $@
    ;;
    "remove"):
    dr_remove $@
    ;;
    "info"):
    dr_info $@
    ;;
    "help"):
    showCommands
    ;;
    *):
    echo "unkown command, use \"cazel help\" to get help."
    ;;
  esac
}


main $@
