#!/bin/bash

declare g_build="build"
declare g_config="depends.json"

function get_project_name()
{
  local config_file=$1
  local project_name=`jq -r ".config.name" $config_file`
  echo $project_name
}

function check_dr_project()
{
  local project_path=$1
  if [ -f $project_path/$g_config ]; then
    return 0
  fi

  return 1
}

function main()
{
  local workspace=`pwd`
  local project=$1
  local project_name

  if [ "$project" == "" ]; then
    project="."
  fi

  if [ ! -d $project ]; then
    echo "Project $project not found."
    return 1
  fi

  check_dr_project $project
  if [ $? -eq 1 ]; then
    echo "Not a dr project"
    return 1
  fi

  cd $project/$g_build
  ./$2
  project_name=`get_project_name ../$g_config`
  cd $workspace

  return 0
}

main $@
