#!/bin/bash

declare g_build="build"
declare g_config="depends.json"

function create_build()
{
  local project=$1
  if [ ! -d $g_build ]; then
    mkdir -p $project/$g_build
    return @?
  fi
  return 0
}

function cmake_with_config()
{
  local config_file=$1
  local cmake_config=`jq -r ".config.cmake" $config_file`
  cmake $cmake_config ..
  return $?
}

function make_with_config()
{
  local config_file=$1
  local make_config=`jq -r ".config.make" $config_file`
  make $make_config
  return $?
}

function get_project_name()
{
  local config_file=$1
  local cmake_config=`jq -r ".config.name" $config_file`
  echo $cmake_config
}

function main()
{
  local workspace=`pwd`
  local project=$1
  local project_name
  if [ "$project" == "" ]; then
    project="."
  fi

  if [ ! -d $project ]; then
    echo "Project $project not found."
    return 1
  fi

  dr_sync $project
  cd $project/
  project_name=`get_project_name $g_config`
  create_build .
  cd $g_build/
  cmake_with_config ../$g_config
  if [ $? -ne 0 ]; then
    cd $workspace
    echo "Cmake failed."
    return 1
  fi
  make_with_config ../$g_config
  if [ $? -ne 0 ]; then
    cd $workspace
    echo "Make failed."
    return 1
  fi

  cd $workspace

  echo "[100%] Built project $project_name."
  return 0
}

main $@
