#!/bin/bash

declare g_config="depends.json"

function check_dr_project()
{
  local project_path=$1
  if [ -f $project_path/$g_config ]; then
    return 0
  fi

  return 1
}

function get_project_name()
{
  local config_file=$1
  local project_name=`jq -r ".config.name" $config_file`
  echo $project_name
}

function get_depends_path()
{
  local config_file=$1
  local depends_path=`jq -r ".config.path" $config_file`
  echo $depends_path
}

function main()
{
  local workspace=`pwd`
  local project=$1
  local project_name

  if [ "$project" == "" ]; then
    project="."
  fi
  check_dr_project $project
  if [ $? -eq 1 ]; then
    echo "Not a dr project"
    return 1
  fi
  if [ ! -d $project ]; then
    echo "Project $project not found."
    return 1
  fi

  cd $project/
  if [ -f depends.cmake ]; then
    rm depends.cmake
  fi
  project_name=`get_project_name $g_config`
  depends_path=`get_depends_path $g_config`
  if [ -d $depends_path ]; then
    rm -rf $depends_path
    rm -rf build
  fi
  cd $workspace

  echo "Removed depends of project $project_name."

  return 0
}

main $@
